name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: mvn package
      - name: tomcat deploy
        run: curl -v -u ${{ secrets.TOMCAT_USERNAME }}:${{ secrets.TOMCAT_PASSWORD }} -T /home/runner/work/spring3-mvc-maven-xml-hello-world/spring3-mvc-maven-xml-hello-world/target/spring3-mvc-maven-xml-hello-world-1.0-SNAPSHOT.war 'http://ec2-3-109-200-244.ap-south-1.compute.amazonaws.com:8081/manager/text/deploy?path=/github_actions_tomcat&update=true'
